name: docker auto build and push

on: push

jobs:
  docker_jobs:
    name: build all Dockerfile(s)
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # For new Dockerfile, copy this section and modify the `file context`.
      - name: build and push docker images
        id: docker_build_pydev
        uses: docker/build-push-action@v2.1.0
        with:
          context: .
          file: ./pydev/Dockerfile
          platforms: linux/amd6
          push: true
          tags: cmsax/pydev:latest
      - name: image digest pydev
        run: echo ${{ steps.docker_build_pydev.outputs.digest }}
