name: docker image ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # For new Dockerfile, copy this section and modify the `file context`.
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./pydev/Dockerfile
          platforms: linux/amd6
          push: true
          tags: cmsax/pydev:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
